---
- hosts: websever
  become: yes
  vars:
    build_number: '{{ BUILD_NUMBER }}'
  tasks:
      
    - name: login to jfrog
      shell: docker login -u siddeshg672@gmail.com -p Siddu@9880 shstechacademynew.jfrog.io  
    
    - name: pull an image
      shell: docker pull shstechacademynew.jfrog.io/appa/frontend/test-managment:{{ BUILD_NUMBER }}

    - name: remove container
      shell: docker rm -f devopsAppDeploy
        
    - name: create a application container
      shell: docker run -id --name devopsAppDeploy -p 8111:8080 shstechacademynew.jfrog.io/appa/frontend/test-managment:{{ BUILD_NUMBER }}
 
   
